### ISSUE TITLE
Add Cloud Composer documentation to pulse-data wiki

### ISSUE THREAD

**Issue by blake-recidiviz** [Recidiviz/pulse-data#3]
**What needs to be done? Why does it need to be done?**
Add and update the pulse-data Recidiviz wiki with the high level overview of how cloud composer is used in the batch processing and overall orchestration. 

Using the process outlined at https://gist.github.com/larrybotha/10650410 to create a 'Wiki PR'.

**Comment by jessex** [comment]
Hey, @blake-recidiviz, I don't think I see any page over on the pulse-data wiki. Was this created or is this being closed for some other reason?

**Comment by jessex** [comment]
Oh I see this was closed because we're in pulse-data, not recidiviz-data. Never mind me!
